### ISSUE TITLE
不要去验证“验证码”了

### ISSUE THREAD

**Issue by fly9i** [qct/douban-movies-crawler#1]
不要去破解验证码了，再写个自动爬匿名代理的爬虫。。

**Comment by qct** [comment]
爬匿名代理的爬虫意思是换着代理去爬么，他应该是有频率限制，估计线程不能开多了，每个线程要睡一会，然后每个代理爬几次就换代理。

**Comment by fly9i** [comment]
建一个免费匿名代理的池子，定期check池子里代理的可用性，限制每代理使用频次，每次fetch优先级选取代理。

**Comment by qct** [comment]
嗯  不错，先弄俩代理试试
